authorName: default
experimentName: example_mnist_pytorch
trialConcurrency: 2
maxExecDuration: 1000h
maxTrialNum: 1000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
localConfig:
  useActiveGpu: true
  maxTrialNumPerGpu: 2
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python3 mobilenet.py
  codeDir: .
  gpuNum: 1
